# Generated by Django 6.0 on 2026-01-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'alerte")),
                ('metric', models.CharField(choices=[('wind_speed', 'Vitesse du Vent'), ('temperature', 'Température'), ('humidity', 'Humidité'), ('pressure', 'Pression'), ('sys_update', 'Mise à jour Système')], max_length=50, verbose_name='Métrique surveillée')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valeur Min (Exclusif)')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valeur Max (Exclusif)')),
                ('message', models.TextField(verbose_name='Message à afficher')),
                ('alert_type', models.CharField(choices=[('success', 'Succès (Vert)'), ('info', 'Info (Bleu)'), ('warning', 'Avertissement (Jaune)'), ('danger', 'Danger (Rouge)'), ('primary', 'Primaire (Bleu Foncé)')], default='info', max_length=20, verbose_name="Type d'alerte")),
                ('icon', models.CharField(default='bi-info-circle-fill', max_length=50, verbose_name='Classe Icône Bootstrap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='SensorFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vent_vitesse', models.FloatField(verbose_name='Vitesse Vent (km/h)')),
                ('vent_dir', models.CharField(max_length=10, verbose_name='Direction Vent (ex: N, S, NW)')),
                ('vent_angle', models.FloatField(verbose_name='Angle Vent (degrés)')),
                ('temperature', models.FloatField(verbose_name='Température (°C)')),
                ('humidite', models.FloatField(verbose_name='Humidité (%)')),
                ('pression', models.FloatField(verbose_name='Pression (hPa)')),
                ('luminosite', models.FloatField(verbose_name='Luminosité (Lux)')),
            ],
        ),
    ]
